name: Build IzPack Installer

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download IzPack 5.2.4 compiler
      run: |
        wget https://izpack.org/downloads/izpack-dist-5.2.4-compiler.zip -O izpack-zip.zip 
        unzip izpack-zip.zip -d izpack

    - name: Build installer
      run: |
        mkdir -p output
        java -cp "izpack/lib/*" com.izforge.izpack.compiler.Compiler \ resources/install.xml -b . -o output/installer.jar

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: IzPack Installer
        path: output/installer.jar
