name: Maven Build IzPack Installer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Package IzPack Installer
        run: mvn clean package -X

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: izpack-installer
          path: target/installer.jar
