name: Build IzPack Installer via Maven

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java & Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build installer
      run: mvn package

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: IzPack Installer
        path: target/installer.jar
